version: 
    '1.0.0.{build}'
image: 
    Visual Studio 2017
configuration: 
    Release
skip_tags: 
    true
before_build:
    - nuget restore
    - nuget install OpenCover -OutputDirectory packages -Version 4.7.922
build_script:
    - msbuild /verbosity:quiet DesignPatterns.sln    
test_script:
    - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe
        -register:user
        -target:"dotnet.exe"
        -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\DesignPatterns.Test\DesignPatterns.Test.csproj"
        -output:"coverage.xml" 
        -filter:"+[*]DesignPatterns.* -[*.Test]*"           
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"        
branches:
  only:
  - master  
cache: 
    '%USERPROFILE%\.nuget\packages'

