version:
    '1.0.0.{build}'
image:
    Visual Studio 2017
configuration:
    Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
  - master
skip_tags:
    true
clone_depth:
    1
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Installing code coverage tools..
  - nuget install OpenCover -OutputDirectory packages -Version 4.7.922  
  # Installing sonar
  - cmd: dotnet tool install --global dotnet-sonarscanner --version 4.6.0
before_build:
    # Display .NET Core version
    - cmd: dotnet --version
build_script:               
    # sonar start
    - cmd: dotnet sonarscanner begin 
        /k:"lmorelato_design-patterns" 
        /o:"lmorelato-github" 
        /d:sonar.host.url="https://sonarcloud.io" 
        /d:sonar.login="eb82da17e782d9556cb765b772b38b58e9a65d9e" 
        /d:sonar.cs.opencover.reportsPaths="c:\projects\design-patterns\coverage.xml"        
    # build & publish
    - cmd: dotnet build DesignPatterns.sln
    - cmd: dotnet publish .\src\DesignPatterns\DesignPatterns.csproj -c Release
artifacts:
    - path: '.\src\DesignPatterns\bin\release\netcoreapp2.2\publish'
      name: artifacts
      type: zip
test_script:
    # Code coverage Report
    - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe
        -register:user
        -target:"dotnet.exe"
        -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\tests\DesignPatterns.Tests\DesignPatterns.Tests.csproj"
        -output:"coverage.xml"
        -filter:"+[*]* -[*.Tests]*"
        -oldStyle
after_test:
  # sonar end
  - cmd: dotnet sonarscanner end /d:sonar.login="eb82da17e782d9556cb765b772b38b58e9a65d9e"
  # Uploading to codecov the code coverage report
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
cache:
    - '%USERPROFILE%\.nuget\packages'
    - packages -> appveyor.yml
    