version: '1.0.0.{build}'

image: Visual Studio 2017
  
init:
  - cmd: git config --global core.autocrlf true 
  
before_build:  
  - choco install opencover.portable
  - choco install codecov
  
build_script:    
    - OpenCover.Console.exe 
            -target:"dotnet.exe" 
            -filter:"+[DesignPatterns.Code*]* -[DesignPatterns.Test*]*" 
            -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full"         
            -register:user 
            -output:.\coverage.xml        
            -oldStyle        
    - codecov -f .\coverage.xml -t ebdb80cb-f40a-403f-9545-7d25dfb5a2e4 

test: off

branches:
  only:
  - master
