version: '1.0.0.{build}'

image: Visual Studio 2017
  
init:
  - cmd: git config --global core.autocrlf true 
  
before_build:  
  - choco install opencover.portable
  - choco install codecov
  
build_script:
    - cmd: dotnet publish ./DesignPatterns.Code/DesignPatterns.Code.csproj
    
    - OpenCover.Console.exe 
            -target:"dotnet.exe" 
            -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full"
            -filter:"+[*]DesignPatterns.* -[*.Test]* -[*.Playground]*"         
            -register:user 
            -output:.\coverage.xml        
            -oldStyle        
    - codecov -f .\coverage.xml -t ebdb80cb-f40a-403f-9545-7d25dfb5a2e4 

test: off

branches:
  only:
  - master

cache:
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml    
